---
title: "Small Enterprise Fund"
author: "Jonathan Steirer"
date: "11/16/2020"
output: html_document
---
---
title: "smallenterprisefund"
author: "Jonathan Steirer"
date: "11/15/2020"
output: html_document
---

```{r}
library("tidyverse")
library("data.table")
```


```{r}
#Import data by reading each excel page as a csv and saving it to a dataframe
df_01_cemeteries = read_csv('/Users/jwste/Documents/DataViz/data_viz_cle/SmallEnterpriseFund/01_Cemeteries_pg428-30.csv')
df_02_golf_course = read_csv('/Users/jwste/Documents/DataViz/data_viz_cle/SmallEnterpriseFund/02_GolfCourse_pg432-33.csv')
df_03_parking_lots = read_csv('/Users/jwste/Documents/DataViz/data_viz_cle/SmallEnterpriseFund/03_PrkingLotsGnrlOp_pg434-36.csv')
df_04_public_auditorium = read_csv('/Users/jwste/Documents/DataViz/data_viz_cle/SmallEnterpriseFund/04_PublicAuditorium_pg440-42.csv')
df_05_cle_wside_mkt = read_csv('/Users/jwste/Documents/DataViz/data_viz_cle/SmallEnterpriseFund/05_WSideMktGeneralOp_444-45.csv')
```



```{r}
#Get the 2017 Values for the Salary section
sef_cemeteries_salary_2017 <- df_01_cemeteries[2:11, 1:2]

sef_parking_lots_salary_2017 <- df_03_parking_lots[2:9, 1:2]
sef_public_auditorium_salary_2017 <- df_04_public_auditorium[2:11, 1:2]
sef_wside_mkt_salary_2017 <- df_05_cle_wside_mkt[2:8, 1:2]
```

```{r}
#Merge all the offices into one dataframe
f_salary_2017 <- Reduce(function(r_x,r_y) merge(x=r_x, y=r_y, by=1, all=TRUE),  
  list(sef_cemeteries_salary_2017, sef_parking_lots_salary_2017, sef_public_auditorium_salary_2017, sef_wside_mkt_salary_2017))
```

```{r}  
#Rename first column
names(f_salary_2017)[1] <- '2017 - Salary and Wages'
names(f_salary_2017)[2] <- 'Cemeteries'

names(f_salary_2017)[3] <- 'Parking Lots General Operations'
names(f_salary_2017)[4] <- 'Public Auditorium General Operaions'
names(f_salary_2017)[5] <- 'Westside Market General Operaions'
```



```{r}
#Get the 2017 Values for the benefits section
sef_cemeteries_benefits_2017 <- df_01_cemeteries[9:21, 1:2]
sef_golf_course_benefits_2017 <- df_02_golf_course[2:3, 1:2]
sef_parking_lots_benefits_2017 <- df_03_parking_lots[11:22, 1:2]
sef_public_auditorium_benefits_2017 <- df_04_public_auditorium[13:26, 1:2]
sef_wside_mkt_benefits_2017 <- df_05_cle_wside_mkt[10:21, 1:2]
```

```{r}
#Merge all the offices into one dataframe
f_benefits_2017 <- Reduce(function(r_x,r_y) merge(x=r_x, y=r_y, by=1, all=TRUE),  
  list(sef_cemeteries_benefits_2017, sef_golf_course_benefits_2017, sef_parking_lots_benefits_2017, sef_public_auditorium_benefits_2017, sef_wside_mkt_benefits_2017))
```

```{r}  
#Rename first column
names(f_benefits_2017)[1] <- '2017 - Benefits'
names(f_benefits_2017)[2] <- 'Cemeteries'
names(f_benefits_2017)[3] <- 'Golf Courses'
names(f_benefits_2017)[4] <- 'Parking Lots General Operations'
names(f_benefits_2017)[5] <- 'Public Auditorium General Operaions'
names(f_benefits_2017)[6] <- 'Westside Market General Operaions'
```



```{r}
#Get the 2017 Values for the others section
sef_cemeteries_others_2017 <- df_01_cemeteries[23:24, 1:2]

sef_parking_lots_others_2017 <- df_03_parking_lots[24:27, 1:2]
sef_public_auditorium_others_2017 <- df_04_public_auditorium[28:29, 1:2]
sef_wside_mkt_others_2017 <- df_05_cle_wside_mkt[23:24, 1:2]
```

```{r}
#Merge all the offices into one dataframe
f_others_2017 <- Reduce(function(r_x,r_y) merge(x=r_x, y=r_y, by=1, all=TRUE),  
  list(sef_cemeteries_others_2017, sef_parking_lots_others_2017, sef_public_auditorium_others_2017, sef_wside_mkt_others_2017))
```

```{r}  
#Rename first column
names(f_others_2017)[1] <- '2017 - Others'
names(f_others_2017)[2] <- 'Cemeteries'

names(f_others_2017)[3] <- 'Parking Lots General Operations'
names(f_others_2017)[4] <- 'Public Auditorium General Operaions'
names(f_others_2017)[5] <- 'Westside Market General Operaions'
```



```{r}
#Get the 2017 Values for the utilities section
sef_cemeteries_utilities_2017 <- df_01_cemeteries[26:31, 1:2]
sef_golf_course_utilities_2017 <- df_02_golf_course[5:9, 1:2]
sef_parking_lots_utilities_2017 <- df_03_parking_lots[29:31, 1:2]
sef_public_auditorium_utilities_2017 <- df_04_public_auditorium[31:35, 1:2]
sef_wside_mkt_utilities_2017 <- df_05_cle_wside_mkt[26:30, 1:2]
```

```{r}
#Merge all the offices into one dataframe
f_utilities_2017 <- Reduce(function(r_x,r_y) merge(x=r_x, y=r_y, by=1, all=TRUE),  
  list(sef_cemeteries_utilities_2017, sef_golf_course_utilities_2017, sef_parking_lots_utilities_2017, sef_public_auditorium_utilities_2017, sef_wside_mkt_utilities_2017))
```

```{r}  
#Rename first column
names(f_utilities_2017)[1] <- '2017 - Utilities'
names(f_utilities_2017)[2] <- 'Cemeteries'
names(f_utilities_2017)[3] <- 'Golf Courses'
names(f_utilities_2017)[4] <- 'Parking Lots General Operations'
names(f_utilities_2017)[5] <- 'Public Auditorium General Operaions'
names(f_utilities_2017)[6] <- 'Westside Market General Operaions'
```


```{r}
#Get the 2017 Values for the contractual section
sef_cemeteries_contractual_2017 <- df_01_cemeteries[33:39, 1:2]
sef_golf_course_contractual_2017 <- df_02_golf_course[11:16, 1:2]
sef_parking_lots_contractual_2017 <- df_03_parking_lots[33:44, 1:2]
sef_public_auditorium_contractual_2017 <- df_04_public_auditorium[37:42, 1:2]
sef_wside_mkt_contractual_2017 <- df_05_cle_wside_mkt[32:38, 1:2]
```

```{r}
#Merge all the offices into one dataframe
f_contractual_2017 <- Reduce(function(r_x,r_y) merge(x=r_x, y=r_y, by=1, all=TRUE),  
  list(sef_cemeteries_contractual_2017, sef_golf_course_contractual_2017, sef_parking_lots_contractual_2017, sef_public_auditorium_contractual_2017, sef_wside_mkt_contractual_2017))
```

```{r}  
#Rename first column
names(f_contractual_2017)[1] <- '2017 - Contractual Services'
names(f_contractual_2017)[2] <- 'Cemeteries'
names(f_contractual_2017)[3] <- 'Golf Courses'
names(f_contractual_2017)[4] <- 'Parking Lots General Operations'
names(f_contractual_2017)[5] <- 'Public Auditorium General Operaions'
names(f_contractual_2017)[6] <- 'Westside Market General Operaions'
```




```{r}
#Get the 2017 Values for the materials section
sef_cemeteries_materials_2017 <- df_01_cemeteries[41:50, 1:2]
sef_golf_course_materials_2017 <- df_02_golf_course[18:25, 1:2]
sef_parking_lots_materials_2017 <- df_03_parking_lots[46:56, 1:2]
sef_public_auditorium_materials_2017 <- df_04_public_auditorium[44:55, 1:2]
sef_wside_mkt_materials_2017 <- df_05_cle_wside_mkt[40:52, 1:2]
```

```{r}
#Merge all the offices into one dataframe
f_materials_2017 <- Reduce(function(r_x,r_y) merge(x=r_x, y=r_y, by=1, all=TRUE),  
  list(sef_cemeteries_materials_2017, sef_golf_course_materials_2017, sef_parking_lots_materials_2017, sef_public_auditorium_materials_2017, sef_wside_mkt_materials_2017))
```

```{r}  
#Rename first column
names(f_materials_2017)[1] <- '2017 - Materials and Supplies'
names(f_materials_2017)[2] <- 'Cemeteries'
names(f_materials_2017)[3] <- 'Golf Courses'
names(f_materials_2017)[4] <- 'Parking Lots General Operations'
names(f_materials_2017)[5] <- 'Public Auditorium General Operaions'
names(f_materials_2017)[6] <- 'Westside Market General Operaions'
```



```{r}
#Get the 2017 Values for the maintenance section
sef_cemeteries_maintenance_2017 <- df_01_cemeteries[52:56, 1:2]
sef_golf_course_maintenance_2017 <- df_02_golf_course[27:30, 1:2]
sef_parking_lots_maintenance_2017 <- df_03_parking_lots[58:62, 1:2]
sef_public_auditorium_maintenance_2017 <- df_04_public_auditorium[57:63, 1:2]
sef_wside_mkt_maintenance_2017 <- df_05_cle_wside_mkt[54:56, 1:2]
```

```{r}
#Merge all the offices into one dataframe
f_maintenance_2017 <- Reduce(function(r_x,r_y) merge(x=r_x, y=r_y, by=1, all=TRUE),  
  list(sef_cemeteries_maintenance_2017, sef_golf_course_maintenance_2017, sef_parking_lots_maintenance_2017, sef_public_auditorium_2017, sef_wside_mkt_maintenance_2017))
```

```{r}  
#Rename first column
names(f_maintenance_2017)[1] <- '2017 - Maintenance'
names(f_maintenance_2017)[2] <- 'Cemeteries'
names(f_maintenance_2017)[3] <- 'Golf Courses'
names(f_maintenance_2017)[4] <- 'Parking Lots General Operations'
names(f_maintenance_2017)[5] <- 'Public Auditorium General Operaions'
names(f_maintenance_2017)[6] <- 'Westside Market General Operaions'
```



```{r}
#Get the 2017 Values for the claims section
sef_cemeteries_claims_2017 <- df_01_cemeteries[58:59, 1:2]
sef_golf_course_claims_2017 <- df_02_golf_course[32:33, 1:2]
sef_parking_lots_claims_2017 <- df_03_parking_lots[64:65, 1:2]
sef_public_auditorium_claims_2017 <- df_04_public_auditorium[65:73, 1:2]
sef_wside_mkt_claims_2017 <- df_05_cle_wside_mkt[58:59, 1:2]
```

```{r}
#Merge all the offices into one dataframe
f_claims_2017 <- Reduce(function(r_x,r_y) merge(x=r_x, y=r_y, by=1, all=TRUE),  
  list(sef_cemeteries_claims_2017, sef_golf_course_claims_2017, sef_parking_lots_claims_2017, sef_public_auditorium_claims_2017, sef_wside_mkt_claims_2017))
```

```{r}  
#Rename first column
names(f_claims_2017)[1] <- '2017 - Claims, Refunds, Maintenance'
names(f_claims_2017)[2] <- 'Cemeteries'
names(f_claims_2017)[3] <- 'Golf Courses'
names(f_claims_2017)[4] <- 'Parking Lots General Operations'
names(f_claims_2017)[5] <- 'Public Auditorium General Operaions'
names(f_claims_2017)[6] <- 'Westside Market General Operaions'
```



```{r}
#Get the 2017 Values for the interdept section
sef_cemeteries_interdept_2017 <- df_01_cemeteries[61:68, 1:2]
sef_golf_course_interdept_2017 <- df_02_golf_course[35:39, 1:2]
sef_parking_lots_interdept_2017 <- df_03_parking_lots[67:73, 1:2]
sef_public_auditorium_interdept_2017 <- df_04_public_auditorium[65:73, 1:2]
sef_wside_mkt_interdept_2017 <- df_05_cle_wside_mkt[61:66, 1:2]
```

```{r}
#Merge all the offices into one dataframe
f_interdept_2017 <- Reduce(function(r_x,r_y) merge(x=r_x, y=r_y, by=1, all=TRUE),  
  list(sef_cemeteries_interdept_2017, sef_golf_course_interdept_2017, sef_parking_lots_interdept_2017, sef_public_auditorium_interdept_2017, sef_wside_mkt_interdept_2017))
```

```{r}  
#Rename first column
names(f_interdept_2017)[1] <- '2017 - Interdept Service Charges'
names(f_interdept_2017)[2] <- 'Cemeteries'
names(f_interdept_2017)[3] <- 'Golf Courses'
names(f_interdept_2017)[4] <- 'Parking Lots General Operations'
names(f_interdept_2017)[5] <- 'Public Auditorium General Operaions'
names(f_interdept_2017)[6] <- 'Westside Market General Operaions'
```



```{r}
#Get the 2017 Values for the revenue section
sef_cemeteries_revenue_2017 <- df_01_cemeteries[71:77, 1:2]
sef_golf_course_revenue_2017 <- df_02_golf_course[42:45, 1:2]
sef_parking_lots_revenue_2017 <- df_03_parking_lots[83:87, 1:2]
sef_public_auditorium_revenue_2017 <- df_04_public_auditorium[76:81, 1:2]
sef_wside_mkt_revenue_2017 <- df_05_cle_wside_mkt[69:72, 1:2]
```

```{r}
#Merge all the offices into one dataframe
f_revenue_2017 <- Reduce(function(r_x,r_y) merge(x=r_x, y=r_y, by=1, all=TRUE),  
  list(sef_cemeteries_revenue_2017, sef_golf_course_revenue_2017, sef_parking_lots_revenue_2017, sef_public_auditorium_revenue_2017, sef_wside_mkt_revenue_2017))
```

```{r}  
#Rename first column
names(f_revenue_2017)[1] <- '2017 - Revenue'
names(f_revenue_2017)[2] <- 'Cemeteries'
names(f_revenue_2017)[3] <- 'Golf Courses'
names(f_revenue_2017)[4] <- 'Parking Lots General Operations'
names(f_revenue_2017)[5] <- 'Public Auditorium General Operaions'
names(f_revenue_2017)[6] <- 'Westside Market General Operaions'
```




```{r}
#Get the 2018 Values for the Salary section
sef_cemeteries_salary_2018 <- df_01_cemeteries[2:11, c(1,3)]

sef_parking_lots_salary_2018 <- df_03_parking_lots[2:9, c(1,3)]
sef_public_auditorium_salary_2018 <- df_04_public_auditorium[2:11, c(1,3)]
sef_wside_mkt_salary_2018 <- df_05_cle_wside_mkt[2:8, c(1,3)]
```

```{r}
#Merge all the offices into one dataframe
f_salary_2018 <- Reduce(function(r_x,r_y) merge(x=r_x, y=r_y, by=1, all=TRUE),  
  list(sef_cemeteries_salary_2018, sef_parking_lots_salary_2018, sef_public_auditorium_salary_2018, sef_wside_mkt_salary_2018))
```

```{r}  
#Rename first column
names(f_salary_2018)[1] <- '2018 - Salary and Wages'
names(f_salary_2018)[2] <- 'Cemeteries'

names(f_salary_2018)[3] <- 'Parking Lots General Operations'
names(f_salary_2018)[4] <- 'Public Auditorium General Operaions'
names(f_salary_2018)[5] <- 'Westside Market General Operaions'
```



```{r}
#Get the 2018 Values for the benefits section
sef_cemeteries_benefits_2018 <- df_01_cemeteries[9:21, c(1,3)]
sef_golf_course_benefits_2018 <- df_02_golf_course[2:3, c(1,3)]
sef_parking_lots_benefits_2018 <- df_03_parking_lots[11:22, c(1,3)]
sef_public_auditorium_benefits_2018 <- df_04_public_auditorium[13:26, c(1,3)]
sef_wside_mkt_benefits_2018 <- df_05_cle_wside_mkt[10:21, c(1,3)]
```

```{r}
#Merge all the offices into one dataframe
f_benefits_2018 <- Reduce(function(r_x,r_y) merge(x=r_x, y=r_y, by=1, all=TRUE),  
  list(sef_cemeteries_benefits_2018, sef_golf_course_benefits_2018, sef_parking_lots_benefits_2018, sef_public_auditorium_benefits_2018, sef_wside_mkt_benefits_2018))
```

```{r}  
#Rename first column
names(f_benefits_2018)[1] <- '2018 - Benefits'
names(f_benefits_2018)[2] <- 'Cemeteries'
names(f_benefits_2018)[3] <- 'Golf Courses'
names(f_benefits_2018)[4] <- 'Parking Lots General Operations'
names(f_benefits_2018)[5] <- 'Public Auditorium General Operaions'
names(f_benefits_2018)[6] <- 'Westside Market General Operaions'
```



```{r}
#Get the 2018 Values for the others section
sef_cemeteries_others_2018 <- df_01_cemeteries[23:24, c(1,3)]

sef_parking_lots_others_2018 <- df_03_parking_lots[24:27, c(1,3)]
sef_public_auditorium_others_2018 <- df_04_public_auditorium[28:29, c(1,3)]
sef_wside_mkt_others_2018 <- df_05_cle_wside_mkt[23:24, c(1,3)]
```

```{r}
#Merge all the offices into one dataframe
f_others_2018 <- Reduce(function(r_x,r_y) merge(x=r_x, y=r_y, by=1, all=TRUE),  
  list(sef_cemeteries_others_2018, sef_parking_lots_others_2018, sef_public_auditorium_others_2018, sef_wside_mkt_others_2018))
```

```{r}  
#Rename first column
names(f_others_2018)[1] <- '2018 - Others'
names(f_others_2018)[2] <- 'Cemeteries'

names(f_others_2018)[3] <- 'Parking Lots General Operations'
names(f_others_2018)[4] <- 'Public Auditorium General Operaions'
names(f_others_2018)[5] <- 'Westside Market General Operaions'
```



```{r}
#Get the 2018 Values for the utilities section
sef_cemeteries_utilities_2018 <- df_01_cemeteries[26:31, c(1,3)]
sef_golf_course_utilities_2018 <- df_02_golf_course[5:9, c(1,3)]
sef_parking_lots_utilities_2018 <- df_03_parking_lots[29:31, c(1,3)]
sef_public_auditorium_utilities_2018 <- df_04_public_auditorium[31:35, c(1,3)]
sef_wside_mkt_utilities_2018 <- df_05_cle_wside_mkt[26:30, c(1,3)]
```

```{r}
#Merge all the offices into one dataframe
f_utilities_2018 <- Reduce(function(r_x,r_y) merge(x=r_x, y=r_y, by=1, all=TRUE),  
  list(sef_cemeteries_utilities_2018, sef_golf_course_utilities_2018, sef_parking_lots_utilities_2018, sef_public_auditorium_utilities_2018, sef_wside_mkt_utilities_2018))
```

```{r}  
#Rename first column
names(f_utilities_2018)[1] <- '2018 - Utilities'
names(f_utilities_2018)[2] <- 'Cemeteries'
names(f_utilities_2018)[3] <- 'Golf Courses'
names(f_utilities_2018)[4] <- 'Parking Lots General Operations'
names(f_utilities_2018)[5] <- 'Public Auditorium General Operaions'
names(f_utilities_2018)[6] <- 'Westside Market General Operaions'
```


```{r}
#Get the 2018 Values for the contractual section
sef_cemeteries_contractual_2018 <- df_01_cemeteries[33:39, c(1,3)]
sef_golf_course_contractual_2018 <- df_02_golf_course[11:16, c(1,3)]
sef_parking_lots_contractual_2018 <- df_03_parking_lots[33:44, c(1,3)]
sef_public_auditorium_contractual_2018 <- df_04_public_auditorium[37:42, c(1,3)]
sef_wside_mkt_contractual_2018 <- df_05_cle_wside_mkt[32:38, c(1,3)]
```

```{r}
#Merge all the offices into one dataframe
f_contractual_2018 <- Reduce(function(r_x,r_y) merge(x=r_x, y=r_y, by=1, all=TRUE),  
  list(sef_cemeteries_contractual_2018, sef_golf_course_contractual_2018, sef_parking_lots_contractual_2018, sef_public_auditorium_contractual_2018, sef_wside_mkt_contractual_2018))
```

```{r}  
#Rename first column
names(f_contractual_2018)[1] <- '2018 - Contractual Services'
names(f_contractual_2018)[2] <- 'Cemeteries'
names(f_contractual_2018)[3] <- 'Golf Courses'
names(f_contractual_2018)[4] <- 'Parking Lots General Operations'
names(f_contractual_2018)[5] <- 'Public Auditorium General Operaions'
names(f_contractual_2018)[6] <- 'Westside Market General Operaions'
```




```{r}
#Get the 2018 Values for the materials section
sef_cemeteries_materials_2018 <- df_01_cemeteries[41:50, c(1,3)]
sef_golf_course_materials_2018 <- df_02_golf_course[18:25, c(1,3)]
sef_parking_lots_materials_2018 <- df_03_parking_lots[46:56, c(1,3)]
sef_public_auditorium_materials_2018 <- df_04_public_auditorium[44:55, c(1,3)]
sef_wside_mkt_materials_2018 <- df_05_cle_wside_mkt[40:52, c(1,3)]
```

```{r}
#Merge all the offices into one dataframe
f_materials_2018 <- Reduce(function(r_x,r_y) merge(x=r_x, y=r_y, by=1, all=TRUE),  
  list(sef_cemeteries_materials_2018, sef_golf_course_materials_2018, sef_parking_lots_materials_2018, sef_public_auditorium_materials_2018, sef_wside_mkt_materials_2018))
```

```{r}  
#Rename first column
names(f_materials_2018)[1] <- '2018 - Materials and Supplies'
names(f_materials_2018)[2] <- 'Cemeteries'
names(f_materials_2018)[3] <- 'Golf Courses'
names(f_materials_2018)[4] <- 'Parking Lots General Operations'
names(f_materials_2018)[5] <- 'Public Auditorium General Operaions'
names(f_materials_2018)[6] <- 'Westside Market General Operaions'
```



```{r}
#Get the 2018 Values for the maintenance section
sef_cemeteries_maintenance_2018 <- df_01_cemeteries[52:56, c(1,3)]
sef_golf_course_maintenance_2018 <- df_02_golf_course[27:30, c(1,3)]
sef_parking_lots_maintenance_2018 <- df_03_parking_lots[58:62, c(1,3)]
sef_public_auditorium_maintenance_2018 <- df_04_public_auditorium[57:63, c(1,3)]
sef_wside_mkt_maintenance_2018 <- df_05_cle_wside_mkt[54:56, c(1,3)]
```

```{r}
#Merge all the offices into one dataframe
f_maintenance_2018 <- Reduce(function(r_x,r_y) merge(x=r_x, y=r_y, by=1, all=TRUE),  
  list(sef_cemeteries_maintenance_2018, sef_golf_course_maintenance_2018, sef_parking_lots_maintenance_2018, sef_public_auditorium_maintenance_2018, sef_wside_mkt_maintenance_2018))
```

```{r}  
#Rename first column
names(f_maintenance_2018)[1] <- '2018 - Maintenance'
names(f_maintenance_2018)[2] <- 'Cemeteries'
names(f_maintenance_2018)[3] <- 'Golf Courses'
names(f_maintenance_2018)[4] <- 'Parking Lots General Operations'
names(f_maintenance_2018)[5] <- 'Public Auditorium General Operaions'
names(f_maintenance_2018)[6] <- 'Westside Market General Operaions'
```



```{r}
#Get the 2018 Values for the claims section
sef_cemeteries_claims_2018 <- df_01_cemeteries[58:59, c(1,3)]
sef_golf_course_claims_2018 <- df_02_golf_course[32:33, c(1,3)]
sef_parking_lots_claims_2018 <- df_03_parking_lots[64:65, c(1,3)]
sef_public_auditorium_claims_2018 <- df_04_public_auditorium[65:73, c(1,3)]
sef_wside_mkt_claims_2018 <- df_05_cle_wside_mkt[58:59, c(1,3)]
```

```{r}
#Merge all the offices into one dataframe
f_claims_2018 <- Reduce(function(r_x,r_y) merge(x=r_x, y=r_y, by=1, all=TRUE),  
  list(sef_cemeteries_claims_2018, sef_golf_course_claims_2018, sef_parking_lots_claims_2018, sef_public_auditorium_claims_2018, sef_wside_mkt_claims_2018))
```

```{r}  
#Rename first column
names(f_claims_2018)[1] <- '2018 - Claims, Refunds, Maintenance'
names(f_claims_2018)[2] <- 'Cemeteries'
names(f_claims_2018)[3] <- 'Golf Courses'
names(f_claims_2018)[4] <- 'Parking Lots General Operations'
names(f_claims_2018)[5] <- 'Public Auditorium General Operaions'
names(f_claims_2018)[6] <- 'Westside Market General Operaions'
```



```{r}
#Get the 2018 Values for the interdept section
sef_cemeteries_interdept_2018 <- df_01_cemeteries[61:68, c(1,3)]
sef_golf_course_interdept_2018 <- df_02_golf_course[35:39, c(1,3)]
sef_parking_lots_interdept_2018 <- df_03_parking_lots[67:73, c(1,3)]
sef_public_auditorium_interdept_2018 <- df_04_public_auditorium[65:73, c(1,3)]
sef_wside_mkt_interdept_2018 <- df_05_cle_wside_mkt[61:66, c(1,3)]
```

```{r}
#Merge all the offices into one dataframe
f_interdept_2018 <- Reduce(function(r_x,r_y) merge(x=r_x, y=r_y, by=1, all=TRUE),  
  list(sef_cemeteries_interdept_2018, sef_golf_course_interdept_2018, sef_parking_lots_interdept_2018, sef_public_auditorium_interdept_2018, sef_wside_mkt_interdept_2018))
```

```{r}  
#Rename first column
names(f_interdept_2018)[1] <- '2018 - Interdept Service Charges'
names(f_interdept_2018)[2] <- 'Cemeteries'
names(f_interdept_2018)[3] <- 'Golf Courses'
names(f_interdept_2018)[4] <- 'Parking Lots General Operations'
names(f_interdept_2018)[5] <- 'Public Auditorium General Operaions'
names(f_interdept_2018)[6] <- 'Westside Market General Operaions'
```



```{r}
#Get the 2018 Values for the revenue section
sef_cemeteries_revenue_2018 <- df_01_cemeteries[71:77, c(1,3)]
sef_golf_course_revenue_2018 <- df_02_golf_course[42:45, c(1,3)]
sef_parking_lots_revenue_2018 <- df_03_parking_lots[83:87, c(1,3)]
sef_public_auditorium_revenue_2018 <- df_04_public_auditorium[76:81, c(1,3)]
sef_wside_mkt_revenue_2018 <- df_05_cle_wside_mkt[69:72, c(1,3)]
```

```{r}
#Merge all the offices into one dataframe
f_revenue_2018 <- Reduce(function(r_x,r_y) merge(x=r_x, y=r_y, by=1, all=TRUE),  
  list(sef_cemeteries_revenue_2018, sef_golf_course_revenue_2018, sef_parking_lots_revenue_2018, sef_public_auditorium_revenue_2018, sef_wside_mkt_revenue_2018))
```

```{r}  
#Rename first column
names(f_revenue_2018)[1] <- '2018 - Revenue'
names(f_revenue_2018)[2] <- 'Cemeteries'
names(f_revenue_2018)[3] <- 'Golf Courses'
names(f_revenue_2018)[4] <- 'Parking Lots General Operations'
names(f_revenue_2018)[5] <- 'Public Auditorium General Operaions'
names(f_revenue_2018)[6] <- 'Westside Market General Operaions'
```




```{r}
#Get the 2019_unaudited Values for the Salary section
sef_cemeteries_salary_2019_unaudited <- df_01_cemeteries[2:11, c(1,4)]

sef_parking_lots_salary_2019_unaudited <- df_03_parking_lots[2:9, c(1,4)]
sef_public_auditorium_salary_2019_unaudited <- df_04_public_auditorium[2:11, c(1,4)]
sef_wside_mkt_salary_2019_unaudited <- df_05_cle_wside_mkt[2:8, c(1,4)]
```

```{r}
#Merge all the offices into one dataframe
f_salary_2019_unaudited <- Reduce(function(r_x,r_y) merge(x=r_x, y=r_y, by=1, all=TRUE),  
  list(sef_cemeteries_salary_2019_unaudited, sef_parking_lots_salary_2019_unaudited, sef_public_auditorium_salary_2019_unaudited, sef_wside_mkt_salary_2019_unaudited))
```

```{r}  
#Rename first column
names(f_salary_2019_unaudited)[1] <- '2019_unaudited - Salary and Wages'
names(f_salary_2019_unaudited)[2] <- 'Cemeteries'

names(f_salary_2019_unaudited)[3] <- 'Parking Lots General Operations'
names(f_salary_2019_unaudited)[4] <- 'Public Auditorium General Operaions'
names(f_salary_2019_unaudited)[5] <- 'Westside Market General Operaions'
```



```{r}
#Get the 2019_unaudited Values for the benefits section
sef_cemeteries_benefits_2019_unaudited <- df_01_cemeteries[9:21, c(1,4)]
sef_golf_course_benefits_2019_unaudited <- df_02_golf_course[2:3, c(1,4)]
sef_parking_lots_benefits_2019_unaudited <- df_03_parking_lots[11:22, c(1,4)]
sef_public_auditorium_benefits_2019_unaudited <- df_04_public_auditorium[13:26, c(1,4)]
sef_wside_mkt_benefits_2019_unaudited <- df_05_cle_wside_mkt[10:21, c(1,4)]
```

```{r}
#Merge all the offices into one dataframe
f_benefits_2019_unaudited <- Reduce(function(r_x,r_y) merge(x=r_x, y=r_y, by=1, all=TRUE),  
  list(sef_cemeteries_benefits_2019_unaudited, sef_golf_course_benefits_2019_unaudited, sef_parking_lots_benefits_2019_unaudited, sef_public_auditorium_benefits_2019_unaudited, sef_wside_mkt_benefits_2019_unaudited))
```

```{r}  
#Rename first column
names(f_benefits_2019_unaudited)[1] <- '2019_unaudited - Benefits'
names(f_benefits_2019_unaudited)[2] <- 'Cemeteries'
names(f_benefits_2019_unaudited)[3] <- 'Golf Courses'
names(f_benefits_2019_unaudited)[4] <- 'Parking Lots General Operations'
names(f_benefits_2019_unaudited)[5] <- 'Public Auditorium General Operaions'
names(f_benefits_2019_unaudited)[6] <- 'Westside Market General Operaions'
```



```{r}
#Get the 2019_unaudited Values for the others section
sef_cemeteries_others_2019_unaudited <- df_01_cemeteries[23:24, c(1,4)]

sef_parking_lots_others_2019_unaudited <- df_03_parking_lots[24:27, c(1,4)]
sef_public_auditorium_others_2019_unaudited <- df_04_public_auditorium[28:29, c(1,4)]
sef_wside_mkt_others_2019_unaudited <- df_05_cle_wside_mkt[23:24, c(1,4)]
```

```{r}
#Merge all the offices into one dataframe
f_others_2019_unaudited <- Reduce(function(r_x,r_y) merge(x=r_x, y=r_y, by=1, all=TRUE),  
  list(sef_cemeteries_others_2019_unaudited, sef_parking_lots_others_2019_unaudited, sef_public_auditorium_others_2019_unaudited, sef_wside_mkt_others_2019_unaudited))
```

```{r}  
#Rename first column
names(f_others_2019_unaudited)[1] <- '2019_unaudited - Others'
names(f_others_2019_unaudited)[2] <- 'Cemeteries'

names(f_others_2019_unaudited)[3] <- 'Parking Lots General Operations'
names(f_others_2019_unaudited)[4] <- 'Public Auditorium General Operaions'
names(f_others_2019_unaudited)[5] <- 'Westside Market General Operaions'
```



```{r}
#Get the 2019_unaudited Values for the utilities section
sef_cemeteries_utilities_2019_unaudited <- df_01_cemeteries[26:31, c(1,4)]
sef_golf_course_utilities_2019_unaudited <- df_02_golf_course[5:9, c(1,4)]
sef_parking_lots_utilities_2019_unaudited <- df_03_parking_lots[29:31, c(1,4)]
sef_public_auditorium_utilities_2019_unaudited <- df_04_public_auditorium[31:35, c(1,4)]
sef_wside_mkt_utilities_2019_unaudited <- df_05_cle_wside_mkt[26:30, c(1,4)]
```

```{r}
#Merge all the offices into one dataframe
f_utilities_2019_unaudited <- Reduce(function(r_x,r_y) merge(x=r_x, y=r_y, by=1, all=TRUE),  
  list(sef_cemeteries_utilities_2019_unaudited, sef_golf_course_utilities_2019_unaudited, sef_parking_lots_utilities_2019_unaudited, sef_public_auditorium_utilities_2019_unaudited, sef_wside_mkt_utilities_2019_unaudited))
```

```{r}  
#Rename first column
names(f_utilities_2019_unaudited)[1] <- '2019_unaudited - Utilities'
names(f_utilities_2019_unaudited)[2] <- 'Cemeteries'
names(f_utilities_2019_unaudited)[3] <- 'Golf Courses'
names(f_utilities_2019_unaudited)[4] <- 'Parking Lots General Operations'
names(f_utilities_2019_unaudited)[5] <- 'Public Auditorium General Operaions'
names(f_utilities_2019_unaudited)[6] <- 'Westside Market General Operaions'
```


```{r}
#Get the 2019_unaudited Values for the contractual section
sef_cemeteries_contractual_2019_unaudited <- df_01_cemeteries[33:39, c(1,4)]
sef_golf_course_contractual_2019_unaudited <- df_02_golf_course[11:16, c(1,4)]
sef_parking_lots_contractual_2019_unaudited <- df_03_parking_lots[33:44, c(1,4)]
sef_public_auditorium_contractual_2019_unaudited <- df_04_public_auditorium[37:42, c(1,4)]
sef_wside_mkt_contractual_2019_unaudited <- df_05_cle_wside_mkt[32:38, c(1,4)]
```

```{r}
#Merge all the offices into one dataframe
f_contractual_2019_unaudited <- Reduce(function(r_x,r_y) merge(x=r_x, y=r_y, by=1, all=TRUE),  
  list(sef_cemeteries_contractual_2019_unaudited, sef_golf_course_contractual_2019_unaudited, sef_parking_lots_contractual_2019_unaudited, sef_public_auditorium_contractual_2019_unaudited, sef_wside_mkt_contractual_2019_unaudited))
```

```{r}  
#Rename first column
names(f_contractual_2019_unaudited)[1] <- '2019_unaudited - Contractual Services'
names(f_contractual_2019_unaudited)[2] <- 'Cemeteries'
names(f_contractual_2019_unaudited)[3] <- 'Golf Courses'
names(f_contractual_2019_unaudited)[4] <- 'Parking Lots General Operations'
names(f_contractual_2019_unaudited)[5] <- 'Public Auditorium General Operaions'
names(f_contractual_2019_unaudited)[6] <- 'Westside Market General Operaions'
```




```{r}
#Get the 2019_unaudited Values for the materials section
sef_cemeteries_materials_2019_unaudited <- df_01_cemeteries[41:50, c(1,4)]
sef_golf_course_materials_2019_unaudited <- df_02_golf_course[18:25, c(1,4)]
sef_parking_lots_materials_2019_unaudited <- df_03_parking_lots[46:56, c(1,4)]
sef_public_auditorium_materials_2019_unaudited <- df_04_public_auditorium[44:55, c(1,4)]
sef_wside_mkt_materials_2019_unaudited <- df_05_cle_wside_mkt[40:52, c(1,4)]
```

```{r}
#Merge all the offices into one dataframe
f_materials_2019_unaudited <- Reduce(function(r_x,r_y) merge(x=r_x, y=r_y, by=1, all=TRUE),  
  list(sef_cemeteries_materials_2019_unaudited, sef_golf_course_materials_2019_unaudited, sef_parking_lots_materials_2019_unaudited, sef_public_auditorium_materials_2019_unaudited, sef_wside_mkt_materials_2019_unaudited))
```

```{r}  
#Rename first column
names(f_materials_2019_unaudited)[1] <- '2019_unaudited - Materials and Supplies'
names(f_materials_2019_unaudited)[2] <- 'Cemeteries'
names(f_materials_2019_unaudited)[3] <- 'Golf Courses'
names(f_materials_2019_unaudited)[4] <- 'Parking Lots General Operations'
names(f_materials_2019_unaudited)[5] <- 'Public Auditorium General Operaions'
names(f_materials_2019_unaudited)[6] <- 'Westside Market General Operaions'
```



```{r}
#Get the 2019_unaudited Values for the maintenance section
sef_cemeteries_maintenance_2019_unaudited <- df_01_cemeteries[52:56, c(1,4)]
sef_golf_course_maintenance_2019_unaudited <- df_02_golf_course[27:30, c(1,4)]
sef_parking_lots_maintenance_2019_unaudited <- df_03_parking_lots[58:62, c(1,4)]
sef_public_auditorium_maintenance_2019_unaudited <- df_04_public_auditorium[57:63, c(1,4)]
sef_wside_mkt_maintenance_2019_unaudited <- df_05_cle_wside_mkt[54:56, c(1,4)]
```

```{r}
#Merge all the offices into one dataframe
f_maintenance_2019_unaudited <- Reduce(function(r_x,r_y) merge(x=r_x, y=r_y, by=1, all=TRUE),  
  list(sef_cemeteries_maintenance_2019_unaudited, sef_golf_course_maintenance_2019_unaudited, sef_parking_lots_maintenance_2019_unaudited, sef_public_auditorium_maintenance_2019_unaudited, sef_wside_mkt_maintenance_2019_unaudited))
```

```{r}  
#Rename first column
names(f_maintenance_2019_unaudited)[1] <- '2019_unaudited - Maintenance'
names(f_maintenance_2019_unaudited)[2] <- 'Cemeteries'
names(f_maintenance_2019_unaudited)[3] <- 'Golf Courses'
names(f_maintenance_2019_unaudited)[4] <- 'Parking Lots General Operations'
names(f_maintenance_2019_unaudited)[5] <- 'Public Auditorium General Operaions'
names(f_maintenance_2019_unaudited)[6] <- 'Westside Market General Operaions'
```



```{r}
#Get the 2019_unaudited Values for the claims section
sef_cemeteries_claims_2019_unaudited <- df_01_cemeteries[58:59, c(1,4)]
sef_golf_course_claims_2019_unaudited <- df_02_golf_course[32:33, c(1,4)]
sef_parking_lots_claims_2019_unaudited <- df_03_parking_lots[64:65, c(1,4)]
sef_public_auditorium_claims_2019_unaudited <- df_04_public_auditorium[65:73, c(1,4)]
sef_wside_mkt_claims_2019_unaudited <- df_05_cle_wside_mkt[58:59, c(1,4)]
```

```{r}
#Merge all the offices into one dataframe
f_claims_2019_unaudited <- Reduce(function(r_x,r_y) merge(x=r_x, y=r_y, by=1, all=TRUE),  
  list(sef_cemeteries_claims_2019_unaudited, sef_golf_course_claims_2019_unaudited, sef_parking_lots_claims_2019_unaudited, sef_public_auditorium_claims_2019_unaudited, sef_wside_mkt_claims_2019_unaudited))
```

```{r}  
#Rename first column
names(f_claims_2019_unaudited)[1] <- '2019_unaudited - Claims, Refunds, Maintenance'
names(f_claims_2019_unaudited)[2] <- 'Cemeteries'
names(f_claims_2019_unaudited)[3] <- 'Golf Courses'
names(f_claims_2019_unaudited)[4] <- 'Parking Lots General Operations'
names(f_claims_2019_unaudited)[5] <- 'Public Auditorium General Operaions'
names(f_claims_2019_unaudited)[6] <- 'Westside Market General Operaions'
```



```{r}
#Get the 2019_unaudited Values for the interdept section
sef_cemeteries_interdept_2019_unaudited <- df_01_cemeteries[61:68, c(1,4)]
sef_golf_course_interdept_2019_unaudited <- df_02_golf_course[35:39, c(1,4)]
sef_parking_lots_interdept_2019_unaudited <- df_03_parking_lots[67:73, c(1,4)]
sef_public_auditorium_interdept_2019_unaudited <- df_04_public_auditorium[65:73, c(1,4)]
sef_wside_mkt_interdept_2019_unaudited <- df_05_cle_wside_mkt[61:66, c(1,4)]
```

```{r}
#Merge all the offices into one dataframe
f_interdept_2019_unaudited <- Reduce(function(r_x,r_y) merge(x=r_x, y=r_y, by=1, all=TRUE),  
  list(sef_cemeteries_interdept_2019_unaudited, sef_golf_course_interdept_2019_unaudited, sef_parking_lots_interdept_2019_unaudited, sef_public_auditorium_interdept_2019_unaudited, sef_wside_mkt_interdept_2019_unaudited))
```

```{r}  
#Rename first column
names(f_interdept_2019_unaudited)[1] <- '2019_unaudited - Interdept Service Charges'
names(f_interdept_2019_unaudited)[2] <- 'Cemeteries'
names(f_interdept_2019_unaudited)[3] <- 'Golf Courses'
names(f_interdept_2019_unaudited)[4] <- 'Parking Lots General Operations'
names(f_interdept_2019_unaudited)[5] <- 'Public Auditorium General Operaions'
names(f_interdept_2019_unaudited)[6] <- 'Westside Market General Operaions'
```



```{r}
#Get the 2019_unaudited Values for the revenue section
sef_cemeteries_revenue_2019_unaudited <- df_01_cemeteries[71:77, c(1,4)]
sef_golf_course_revenue_2019_unaudited <- df_02_golf_course[42:45, c(1,4)]
sef_parking_lots_revenue_2019_unaudited <- df_03_parking_lots[83:87, c(1,4)]
sef_public_auditorium_revenue_2019_unaudited <- df_04_public_auditorium[76:81, c(1,4)]
sef_wside_mkt_revenue_2019_unaudited <- df_05_cle_wside_mkt[69:72, c(1,4)]
```

```{r}
#Merge all the offices into one dataframe
f_revenue_2019_unaudited <- Reduce(function(r_x,r_y) merge(x=r_x, y=r_y, by=1, all=TRUE),  
  list(sef_cemeteries_revenue_2019_unaudited, sef_golf_course_revenue_2019_unaudited, sef_parking_lots_revenue_2019_unaudited, sef_public_auditorium_revenue_2019_unaudited, sef_wside_mkt_revenue_2019_unaudited))
```

```{r}  
#Rename first column
names(f_revenue_2019_unaudited)[1] <- '2019_unaudited - Revenue'
names(f_revenue_2019_unaudited)[2] <- 'Cemeteries'
names(f_revenue_2019_unaudited)[3] <- 'Golf Courses'
names(f_revenue_2019_unaudited)[4] <- 'Parking Lots General Operations'
names(f_revenue_2019_unaudited)[5] <- 'Public Auditorium General Operaions'
names(f_revenue_2019_unaudited)[6] <- 'Westside Market General Operaions'
```




```{r}
#Get the 2019_budget Values for the Salary section
sef_cemeteries_salary_2019_budget <- df_01_cemeteries[2:11, c(1,5)]

sef_parking_lots_salary_2019_budget <- df_03_parking_lots[2:9, c(1,5)]
sef_public_auditorium_salary_2019_budget <- df_04_public_auditorium[2:11, c(1,5)]
sef_wside_mkt_salary_2019_budget <- df_05_cle_wside_mkt[2:8, c(1,5)]
```

```{r}
#Merge all the offices into one dataframe
f_salary_2019_budget <- Reduce(function(r_x,r_y) merge(x=r_x, y=r_y, by=1, all=TRUE),  
  list(sef_cemeteries_salary_2019_budget, sef_parking_lots_salary_2019_budget, sef_public_auditorium_salary_2019_budget, sef_wside_mkt_salary_2019_budget))
```

```{r}  
#Rename first column
names(f_salary_2019_budget)[1] <- '2019_budget - Salary and Wages'
names(f_salary_2019_budget)[2] <- 'Cemeteries'

names(f_salary_2019_budget)[3] <- 'Parking Lots General Operations'
names(f_salary_2019_budget)[4] <- 'Public Auditorium General Operaions'
names(f_salary_2019_budget)[5] <- 'Westside Market General Operaions'
```



```{r}
#Get the 2019_budget Values for the benefits section
sef_cemeteries_benefits_2019_budget <- df_01_cemeteries[9:21, c(1,5)]
sef_golf_course_benefits_2019_budget <- df_02_golf_course[2:3, c(1,5)]
sef_parking_lots_benefits_2019_budget <- df_03_parking_lots[11:22, c(1,5)]
sef_public_auditorium_benefits_2019_budget <- df_04_public_auditorium[13:26, c(1,5)]
sef_wside_mkt_benefits_2019_budget <- df_05_cle_wside_mkt[10:21, c(1,5)]
```

```{r}
#Merge all the offices into one dataframe
f_benefits_2019_budget <- Reduce(function(r_x,r_y) merge(x=r_x, y=r_y, by=1, all=TRUE),  
  list(sef_cemeteries_benefits_2019_budget, sef_golf_course_benefits_2019_budget, sef_parking_lots_benefits_2019_budget, sef_public_auditorium_benefits_2019_budget, sef_wside_mkt_benefits_2019_budget))
```

```{r}  
#Rename first column
names(f_benefits_2019_budget)[1] <- '2019_budget - Benefits'
names(f_benefits_2019_budget)[2] <- 'Cemeteries'
names(f_benefits_2019_budget)[3] <- 'Golf Courses'
names(f_benefits_2019_budget)[4] <- 'Parking Lots General Operations'
names(f_benefits_2019_budget)[5] <- 'Public Auditorium General Operaions'
names(f_benefits_2019_budget)[6] <- 'Westside Market General Operaions'
```



```{r}
#Get the 2019_budget Values for the others section
sef_cemeteries_others_2019_budget <- df_01_cemeteries[23:24, c(1,5)]

sef_parking_lots_others_2019_budget <- df_03_parking_lots[24:27, c(1,5)]
sef_public_auditorium_others_2019_budget <- df_04_public_auditorium[28:29, c(1,5)]
sef_wside_mkt_others_2019_budget <- df_05_cle_wside_mkt[23:24, c(1,5)]
```

```{r}
#Merge all the offices into one dataframe
f_others_2019_budget <- Reduce(function(r_x,r_y) merge(x=r_x, y=r_y, by=1, all=TRUE),  
  list(sef_cemeteries_others_2019_budget, sef_parking_lots_others_2019_budget, sef_public_auditorium_others_2019_budget, sef_wside_mkt_others_2019_budget))
```

```{r}  
#Rename first column
names(f_others_2019_budget)[1] <- '2019_budget - Others'
names(f_others_2019_budget)[2] <- 'Cemeteries'

names(f_others_2019_budget)[3] <- 'Parking Lots General Operations'
names(f_others_2019_budget)[4] <- 'Public Auditorium General Operaions'
names(f_others_2019_budget)[5] <- 'Westside Market General Operaions'
```



```{r}
#Get the 2019_budget Values for the utilities section
sef_cemeteries_utilities_2019_budget <- df_01_cemeteries[26:31, c(1,5)]
sef_golf_course_utilities_2019_budget <- df_02_golf_course[5:9, c(1,5)]
sef_parking_lots_utilities_2019_budget <- df_03_parking_lots[29:31, c(1,5)]
sef_public_auditorium_utilities_2019_budget <- df_04_public_auditorium[31:35, c(1,5)]
sef_wside_mkt_utilities_2019_budget <- df_05_cle_wside_mkt[26:30, c(1,5)]
```

```{r}
#Merge all the offices into one dataframe
f_utilities_2019_budget <- Reduce(function(r_x,r_y) merge(x=r_x, y=r_y, by=1, all=TRUE),  
  list(sef_cemeteries_utilities_2019_budget, sef_golf_course_utilities_2019_budget, sef_parking_lots_utilities_2019_budget, sef_public_auditorium_utilities_2019_budget, sef_wside_mkt_utilities_2019_budget))
```

```{r}  
#Rename first column
names(f_utilities_2019_budget)[1] <- '2019_budget - Utilities'
names(f_utilities_2019_budget)[2] <- 'Cemeteries'
names(f_utilities_2019_budget)[3] <- 'Golf Courses'
names(f_utilities_2019_budget)[4] <- 'Parking Lots General Operations'
names(f_utilities_2019_budget)[5] <- 'Public Auditorium General Operaions'
names(f_utilities_2019_budget)[6] <- 'Westside Market General Operaions'
```


```{r}
#Get the 2019_budget Values for the contractual section
sef_cemeteries_contractual_2019_budget <- df_01_cemeteries[33:39, c(1,5)]
sef_golf_course_contractual_2019_budget <- df_02_golf_course[11:16, c(1,5)]
sef_parking_lots_contractual_2019_budget <- df_03_parking_lots[33:44, c(1,5)]
sef_public_auditorium_contractual_2019_budget <- df_04_public_auditorium[37:42, c(1,5)]
sef_wside_mkt_contractual_2019_budget <- df_05_cle_wside_mkt[32:38, c(1,5)]
```

```{r}
#Merge all the offices into one dataframe
f_contractual_2019_budget <- Reduce(function(r_x,r_y) merge(x=r_x, y=r_y, by=1, all=TRUE),  
  list(sef_cemeteries_contractual_2019_budget, sef_golf_course_contractual_2019_budget, sef_parking_lots_contractual_2019_budget, sef_public_auditorium_contractual_2019_budget, sef_wside_mkt_contractual_2019_budget))
```

```{r}  
#Rename first column
names(f_contractual_2019_budget)[1] <- '2019_budget - Contractual Services'
names(f_contractual_2019_budget)[2] <- 'Cemeteries'
names(f_contractual_2019_budget)[3] <- 'Golf Courses'
names(f_contractual_2019_budget)[4] <- 'Parking Lots General Operations'
names(f_contractual_2019_budget)[5] <- 'Public Auditorium General Operaions'
names(f_contractual_2019_budget)[6] <- 'Westside Market General Operaions'
```




```{r}
#Get the 2019_budget Values for the materials section
sef_cemeteries_materials_2019_budget <- df_01_cemeteries[41:50, c(1,5)]
sef_golf_course_materials_2019_budget <- df_02_golf_course[18:25, c(1,5)]
sef_parking_lots_materials_2019_budget <- df_03_parking_lots[46:56, c(1,5)]
sef_public_auditorium_materials_2019_budget <- df_04_public_auditorium[44:55, c(1,5)]
sef_wside_mkt_materials_2019_budget <- df_05_cle_wside_mkt[40:52, c(1,5)]
```

```{r}
#Merge all the offices into one dataframe
f_materials_2019_budget <- Reduce(function(r_x,r_y) merge(x=r_x, y=r_y, by=1, all=TRUE),  
  list(sef_cemeteries_materials_2019_budget, sef_golf_course_materials_2019_budget, sef_parking_lots_materials_2019_budget, sef_public_auditorium_materials_2019_budget, sef_wside_mkt_materials_2019_budget))
```

```{r}  
#Rename first column
names(f_materials_2019_budget)[1] <- '2019_budget - Materials and Supplies'
names(f_materials_2019_budget)[2] <- 'Cemeteries'
names(f_materials_2019_budget)[3] <- 'Golf Courses'
names(f_materials_2019_budget)[4] <- 'Parking Lots General Operations'
names(f_materials_2019_budget)[5] <- 'Public Auditorium General Operaions'
names(f_materials_2019_budget)[6] <- 'Westside Market General Operaions'
```



```{r}
#Get the 2019_budget Values for the maintenance section
sef_cemeteries_maintenance_2019_budget <- df_01_cemeteries[52:56, c(1,5)]
sef_golf_course_maintenance_2019_budget <- df_02_golf_course[27:30, c(1,5)]
sef_parking_lots_maintenance_2019_budget <- df_03_parking_lots[58:62, c(1,5)]
sef_public_auditorium_maintenance_2019_budget <- df_04_public_auditorium[57:63, c(1,5)]
sef_wside_mkt_maintenance_2019_budget <- df_05_cle_wside_mkt[54:56, c(1,5)]
```

```{r}
#Merge all the offices into one dataframe
f_maintenance_2019_budget <- Reduce(function(r_x,r_y) merge(x=r_x, y=r_y, by=1, all=TRUE),  
  list(sef_cemeteries_maintenance_2019_budget, sef_golf_course_maintenance_2019_budget, sef_parking_lots_maintenance_2019_budget, sef_public_auditorium_maintenance_2019_budget, sef_wside_mkt_maintenance_2019_budget))
```

```{r}  
#Rename first column
names(f_maintenance_2019_budget)[1] <- '2019_budget - Maintenance'
names(f_maintenance_2019_budget)[2] <- 'Cemeteries'
names(f_maintenance_2019_budget)[3] <- 'Golf Courses'
names(f_maintenance_2019_budget)[4] <- 'Parking Lots General Operations'
names(f_maintenance_2019_budget)[5] <- 'Public Auditorium General Operaions'
names(f_maintenance_2019_budget)[6] <- 'Westside Market General Operaions'
```



```{r}
#Get the 2019_budget Values for the claims section
sef_cemeteries_claims_2019_budget <- df_01_cemeteries[58:59, c(1,5)]
sef_golf_course_claims_2019_budget <- df_02_golf_course[32:33, c(1,5)]
sef_parking_lots_claims_2019_budget <- df_03_parking_lots[64:65, c(1,5)]
sef_public_auditorium_claims_2019_budget <- df_04_public_auditorium[65:73, c(1,5)]
sef_wside_mkt_claims_2019_budget <- df_05_cle_wside_mkt[58:59, c(1,5)]
```

```{r}
#Merge all the offices into one dataframe
f_claims_2019_budget <- Reduce(function(r_x,r_y) merge(x=r_x, y=r_y, by=1, all=TRUE),  
  list(sef_cemeteries_claims_2019_budget, sef_golf_course_claims_2019_budget, sef_parking_lots_claims_2019_budget, sef_public_auditorium_claims_2019_budget, sef_wside_mkt_claims_2019_budget))
```

```{r}  
#Rename first column
names(f_claims_2019_budget)[1] <- '2019_budget - Claims, Refunds, Maintenance'
names(f_claims_2019_budget)[2] <- 'Cemeteries'
names(f_claims_2019_budget)[3] <- 'Golf Courses'
names(f_claims_2019_budget)[4] <- 'Parking Lots General Operations'
names(f_claims_2019_budget)[5] <- 'Public Auditorium General Operaions'
names(f_claims_2019_budget)[6] <- 'Westside Market General Operaions'
```



```{r}
#Get the 2019_budget Values for the interdept section
sef_cemeteries_interdept_2019_budget <- df_01_cemeteries[61:68, c(1,5)]
sef_golf_course_interdept_2019_budget <- df_02_golf_course[35:39, c(1,5)]
sef_parking_lots_interdept_2019_budget <- df_03_parking_lots[67:73, c(1,5)]
sef_public_auditorium_interdept_2019_budget <- df_04_public_auditorium[65:73, c(1,5)]
sef_wside_mkt_interdept_2019_budget <- df_05_cle_wside_mkt[61:66, c(1,5)]
```

```{r}
#Merge all the offices into one dataframe
f_interdept_2019_budget <- Reduce(function(r_x,r_y) merge(x=r_x, y=r_y, by=1, all=TRUE),  
  list(sef_cemeteries_interdept_2019_budget, sef_golf_course_interdept_2019_budget, sef_parking_lots_interdept_2019_budget, sef_public_auditorium_interdept_2019_budget, sef_wside_mkt_interdept_2019_budget))
```

```{r}  
#Rename first column
names(f_interdept_2019_budget)[1] <- '2019_budget - Interdept Service Charges'
names(f_interdept_2019_budget)[2] <- 'Cemeteries'
names(f_interdept_2019_budget)[3] <- 'Golf Courses'
names(f_interdept_2019_budget)[4] <- 'Parking Lots General Operations'
names(f_interdept_2019_budget)[5] <- 'Public Auditorium General Operaions'
names(f_interdept_2019_budget)[6] <- 'Westside Market General Operaions'
```



```{r}
#Get the 2019_budget Values for the revenue section
sef_cemeteries_revenue_2019_budget <- df_01_cemeteries[71:77, c(1,5)]
sef_golf_course_revenue_2019_budget <- df_02_golf_course[42:45, c(1,5)]
sef_parking_lots_revenue_2019_budget <- df_03_parking_lots[83:87, c(1,5)]
sef_public_auditorium_revenue_2019_budget <- df_04_public_auditorium[76:81, c(1,5)]
sef_wside_mkt_revenue_2019_budget <- df_05_cle_wside_mkt[69:72, c(1,5)]
```

```{r}
#Merge all the offices into one dataframe
f_revenue_2019_budget <- Reduce(function(r_x,r_y) merge(x=r_x, y=r_y, by=1, all=TRUE),  
  list(sef_cemeteries_revenue_2019_budget, sef_golf_course_revenue_2019_budget, sef_parking_lots_revenue_2019_budget, sef_public_auditorium_revenue_2019_budget, sef_wside_mkt_revenue_2019_budget))
```

```{r}  
#Rename first column
names(f_revenue_2019_budget)[1] <- '2019_budget - Revenue'
names(f_revenue_2019_budget)[2] <- 'Cemeteries'
names(f_revenue_2019_budget)[3] <- 'Golf Courses'
names(f_revenue_2019_budget)[4] <- 'Parking Lots General Operations'
names(f_revenue_2019_budget)[5] <- 'Public Auditorium General Operaions'
names(f_revenue_2019_budget)[6] <- 'Westside Market General Operaions'
```