---
title: "all_capital_outlay_2017"
author: "Taylor"
date: "9/22/2020"
output: html_document
---
## INTERNAL SERVICE FUND
#Import data by reading each excel page as a csv and saving it to a dataframe
```{r}
df_01_sinking_fund_gen_op = read_csv('/Users/taylorjohnston/Desktop/Repositories/cle-budget/InternalServiceFund/01_SinkingFundGenOp_pg465.csv')
df_02_telephone_exc = read_csv('/Users/taylorjohnston/Desktop/Repositories/cle-budget/InternalServiceFund/02_TelephoneExchange_pg467-68.csv')
df_03_radio_comm = read_csv('/Users/taylorjohnston/Desktop/Repositories/cle-budget/InternalServiceFund/03_OfficeofRadioComm_pg472-73.csv')
df_04_motor_vehicle_mtn = read_csv('/Users/taylorjohnston/Desktop/Repositories/cle-budget/InternalServiceFund/04_MotorVehicleMtn_pg477-79.csv')
df_05_printing_reprod = read_csv('/Users/taylorjohnston/Desktop/Repositories/cle-budget/InternalServiceFund/05_Printing&Reproduc_pg482-83.csv')
df_06_health_insurance_fund = read_csv('/Users/taylorjohnston/Desktop/Repositories/cle-budget/InternalServiceFund/06_HealthSelfInsuranceFund_pg488.csv')
df_07_prescription_self_insurance_fund = read_csv('/Users/taylorjohnston/Desktop/Repositories/cle-budget/InternalServiceFund/07_PrscptnSelfInsrncFund_pg489.csv')
df_08_CCA_income_tax = read_csv('/Users/taylorjohnston/Desktop/Repositories/cle-budget/InternalServiceFund/08_CCAIncomeTaxAdmin_pg493-95.csv')
```

#Get the 2017 Values for the Capital Outlay section
```{r}
ISF_radio_comm_capital_outlay <- df_03_radio_comm[55:58, 1:5]
```

#Merge all the offices into one dataframe

```{r}
all_capital_outlay <- Reduce(function(r_x,r_y) merge(x=r_x, y=r_y, by=1, all=TRUE),  
  list(ISF_radio_comm_capital_outlay))
```

#Rename first column
```{r}
names(all_capital_outlay)[1] <- 'capital_outlay'
names(all_capital_outlay)[2] <- 'Office of Radio Communication 2017'
names(all_capital_outlay)[3] <- 'Office of Radio Communication 2018'
names(all_capital_outlay)[4] <- 'Office of Radio Communication 2019'
names(all_capital_outlay)[5] <- 'Office of Radio Communication 2020'
all_capital_outlay[4,1] <- "Total" #renaming row to "total"
all_capital_outlay <- clean_names(all_capital_outlay) #cleans the column names
```

#Create file
```{r}
write.csv(all_capital_outlay,"all_capital_outlay.csv")
```
